steps:
  - name: 'maven:3.9-jdk-21'
    args: ['package']
    env:
    - 'GOOGLE_RUNTIME_VERSION=21'
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '--tag=gcr.io/$PROJECT_ID/lookatsoap', '.']
images: ['gcr.io/$PROJECT_ID/lookatsoap']

options:
  logging: CLOUD_LOGGING_ONLY