quarkus:
  log:
    category:
      "org.apache.cxf":
        level: DEBUG

      "io.quarkiverse.cxf":
        level: DEBUG

  cxf:
    path: /soap
    endpoint:
      "/sayhello":
        implementor: nl.ilovecoding.lookatsoap.HelloServiceImpl
        handlers: nl.ilovecoding.lookatsoap.MessageHandler
        features: org.apache.cxf.ws.addressing.WSAddressingFeature
        logging:
          enabled: true
          pretty: true


  http:
    auth:
      basic: true

  security:
    users:
      embedded:
        enabled: true
        plain-text: true
        users:
          marcus: marcus12
        roles:
          marcus: admin

